version: "3.3"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
  app:
    image: node:12-alpine
    command: sh -c "rm -rf /app/node_modules && npm install && npm install -g nodemon && yarn install && yarn run dev"
    ports:
      - set_port:3000
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

volumes:
  todo-mysql-data:

